### ISSUE TITLE
Production requirements listed as dev requirements

### ISSUE THREAD

**Issue by georgiana-b** [NextGeoss/ckanext-nextgeossdeadoralive#1]
This extension cannot be used without the dependencies in the `dev_dependencies.txt` which means they are not dev dependencies. Could you pls move them to the appropriate file and add instructions to the README so that people who try to install the extension know that they also have to run 

`pip install -r https://raw.githubusercontent.com/NextGeoss/ckanext-nextgeossdeadoralive/master/requirements.txt`.

**Comment by ToniDSHG** [comment]
Hi @georgiana-b , we have been a little busy with another project, i will review tomorrow all the issues of this repo and the other one

**Comment by ToniDSHG** [comment]
Hi @georgiana-b , this is not neccesary, because the setup.py is configured to install this dependencies when you run the pip install to install the extension

**Comment by joaandrade** [comment]
@georgiana-b is this issue solved?

**Comment by georgiana-b** [comment]
Yes, this has more to do with our Docker setup than the library. Closing.
